from modules.authorization import check_role
from modules.connect_db import c, connection
import mysql.connector

@check_role("admin")
def add_recipe():
    print("Enter recipe name: ")
    recipe_name = input()
    print("Enter recipe description: ")
    recipe_descr = input()

    # Take input for the number of raw materials
    num_raw_materials = int(input("Enter the number of raw materials: "))

    raw_materials = []  # List to store raw materials and their quantities

    # Take input for each raw material and quantity
    for i in range(num_raw_materials):
        print(f"Enter name of raw material {i+1}: ")
        raw_material_name = input()
        print(f"Enter quantity required for {raw_material_name}: ")
        raw_material_quantity = float(input())
        raw_materials.append((raw_material_name, raw_material_quantity))

    try:
        # Call the add_recipe stored procedure with recipe_name, recipe_price, and raw_materials
        c.callproc('add_recipe', (recipe_name, recipe_descr))

        # Retrieve the recipe_id generated by the stored procedure
        c.execute("SELECT LAST_INSERT_ID();")
        recipe_id = c.fetchone()[0]

        # Add raw materials to the recipe
        print(raw_materials)
        for raw_material in raw_materials:
            print(raw_material[0], raw_material[1])
            c.callproc('add_raw_materials_to_recipe', (recipe_id, raw_material[0], raw_material[1]))
            connection.commit()

        print("Recipe added successfully")

    except mysql.connector.Error as err:
        print(f"Error: {err}")

    return
